### ISSUE TITLE
Main checklist

### ISSUE THREAD

**Issue by CinnamonRolls1** [ryan-rozario/web-scraper-deploy-heroku#16]
- [ ] Script to get SQL data of news articles and run (both) clustering on them, and then store it in a database

- [ ] Summarize each cluster into articles and save them into database
- [ ] Populate frontend with these articles from database
